### ISSUE TITLE
不触发或触发时机错误

### ISSUE THREAD

**Issue by czlh** [YorkChan94/three-onEvent#2]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="js/threejs/three.js"></script>
    <script src="js/onEvent.js"></script>
    <script src="js/jquery-3.2.1.min.js"></script>
    <style>
        *{
            margin: 0;
        }
        div{
            float: left;
        }
        #canvasContainer{
            width: 80%;
        }

        #pramsContainer{
            width: 20%;
        }
    </style>
    <script src="js/threejs/loaders/OBJLoader.js"></script>
    <script src="js/threejs/loaders/MTLLoader.js"></script>
    <script src="js/threejs/controls/OrbitControls.js"></script>
    <script src="./js/threejs/libs/dat.gui.min.js"></script>
</head>
<body>
<div id="canvasContainer"></div>
<div id="pramsContainer"></div>

<script>
    $(function () {
        $('div').height(window.innerHeight);
        var canvasContainer = $('#canvasContainer');

        var canvasWidth = canvasContainer.width();
        var canvasHeight = canvasContainer.height();
        var renderer,scene,camera,light,controllers,gui;
        var objects=[];

        function initScene(){
            scene = new THREE.Scene();
        }
        
        function initRenderer() {
            renderer = new THREE.WebGLRenderer();
            renderer.setSize(canvasWidth,canvasHeight);
            renderer.setClearColor(0xeeeeee);

            canvasContainer.append(renderer.domElement);
        }

        function initCamera(){
            camera = new THREE.PerspectiveCamera(75,canvasWidth/canvasHeight,0.1,1000);
            camera.position.set(-30,40,30);
            camera.lookAt(scene.position);
            scene.add(camera);
        }

        function enableEvent() {
            THREE.onEvent(scene,camera);
        }

        function initLight(){
            light = new THREE.AmbientLight(0x0c0c0c);
            scene.add(light);

            var spotLight = new THREE.SpotLight(0xffffff);
            spotLight.position.set(-40, 60, -10);
            spotLight.castShadow = true;
            scene.add(spotLight);
        }

        function addAxis(){
            var axes=new THREE.AxisHelper(200);
            scene.add(axes);
        }

        function initDatGui() {
            controllers = new (function () {
                this.rotationSpeed = 0.02;
                this.addObjects = function () {

                    var cubeSize = Math.ceil((Math.random() * 3));
                    var cubeGeometry = new THREE.BoxGeometry(cubeSize, cubeSize, cubeSize);
                    var cubeMaterial = new THREE.MeshLambertMaterial({color: Math.random() * 0xffffff});
                    var cube = new THREE.Mesh(cubeGeometry, cubeMaterial);

                    cube.name = "cube-" + scene.children.length;

                    cube.position.x = -30 + Math.round((Math.random() * 100));
                    cube.position.y = Math.round((Math.random() * 5));
                    cube.position.z = -20 + Math.round((Math.random() * 100));

                    // add the cube to the scene
                    scene.add(cube);

                    cube.on('hover',function (m) {
                        console.log(m);
                    });
                };
            });

            gui = new dat.GUI();
            gui.add(controllers, 'rotationSpeed',0,0.5);
            gui.add(controllers,'addObjects');
        }

        function initObjects() {

            for (var i=0;i<0;i++){
                var geometry = new THREE.BoxGeometry(20,20,20);
                var material = new THREE.MeshLambertMaterial({color:Math.random()*0xffffff});
                var boxMesh = new THREE.Mesh(geometry,material);
                boxMesh.position.x=-30+Math.round(Math.random()*200);
                boxMesh.position.y=Math.round(Math.random()*5);
                boxMesh.position.z=-20+Math.round(Math.random()*200);
                scene.add(boxMesh);
                boxMesh.on('hover',function (m) {
                    console.log(m);
                });

                objects.push(boxMesh);
            }
        }

        function render() {
//            scene.traverse(function (o) {
//                if(o instanceof  THREE.Mesh){
//                    o.rotateX(controllers.rotationSpeed);
//                    o.rotateY(controllers.rotationSpeed);
//                    o.rotateZ(controllers.rotationSpeed);
//                }
//            });
            window.requestAnimationFrame(render);
            renderer.render(scene,camera);
        }

        function initControls(){
            var orbitControls = new THREE.OrbitControls(camera,renderer.domElement);
            orbitControls.addEventListener('change',render);
        }

        initScene();
        initRenderer();
        initCamera();
        enableEvent();
        initLight();
        addAxis();
        initDatGui();
        initControls();
        render();

    });

</script>
</body>
</html>

**Comment by YorkChan94** [comment]
try this: justify the order <script src="js/jquery-3.2.1.min.js"></script><script src="js/threejs/three.js"></script> <script src="js/onEvent.js"></script> 
add jquery before onEvent.Maybe jq overwrite the mouse event
